name: RubidiaMonsters
author: pmilon
version: 2.0
api-version: 1.13
description: The mob management system of Rubidia server.
main: me.pmilon.RubidiaMonsters.RubidiaMonstersPlugin
softdepend: [RubidiaQuests]
loadbefore: [RubidiaCore]
commands:
  killall:
    description: Kills all the monsters loaded
    aliases: ka
  regions:
    description: Opens regions menu
    aliases: rgs