name: RubidiaManager
author: pmilon
version: 2.0
api-version: 1.15
description: The Manager plugin of Rubidias server.
main: me.pmilon.RubidiaManager.RubidiaManagerPlugin
softdepend: [RubidiaCore, RubidiaGuilds, WorldEdit, Multiverse-Core]
commands:
  chunk:
    description: Chunk management.
    aliases: chk
  chunks:
    description: Chunks management.
    aliases: chks