name: RubidiaManager
author: pmilon
version: 2.0
api-version: 1.13
description: The Manager plugin of Rubidias server.
main: me.pmilon.RubidiaManager.RubidiaManagerPlugin
softdepend: [Multiverse-Core]
loadbefore: [RubidiaCore, RubidiaGuilds, RubidiaMonsters, RubidiaQuests, RubidiaPets]
commands:
  chunk:
    description: Chunk management.
    aliases: chk
  chunks:
    description: Chunks management.
    aliases: chks